### ISSUE TITLE
Tracks can get out of sync after panning

### ISSUE THREAD

**Issue by helgathorv** [aidenlab/juicebox.js#219]
When testing with the sample data with the paper: 
I found that if I zoomed in quite a bit, and then did a lot of panning,  I could easily get into a state where the tracks were obviously out of sync - with respect to one another and with respect to the contact map. When the view included the centromere gap it was easy to see if things were out of sync because the gaps didn't line up.
Sometimes half the track seemed to be missing.

**Comment by jrobinso** [comment]
I'm refactoring loading and painting to keep everything in sync.   It sounds major but its not.

The "missing track" is caused by the multi-locus bug in IGV.   When off diagonal we basically have a multi-locus view in juicebox.    I'm undecided now if I will fix this in igv.js,  or patch it in juicebox and fix igv.js later.

**Comment by jrobinso** [comment]
Test url: http://bit.ly/2ihDJkF

Dev url  (modify as needed):  http://localhost/hic-viz/examples/website/juicebox-dev.html?juiceboxURL=http://bit.ly/2ihDI05

**Comment by jrobinso** [comment]
A less challenging resolution:  http://bit.ly/2Ah7bOx
