### ISSUE TITLE
Chr 2 vs 3 not working

### ISSUE THREAD

**Issue by sa501428** [aidenlab/juicebox.js#66]
http://igv.org/web/jb/hic.html?colorScale=153.95679258062705&hicUrl=https%3A%2F%2Fhicfiles.s3.amazonaws.com%2Fhiseq%2Fgm12878%2Fin-situ%2FHIC047.hic

1 vs 2 seems to work; 2 vs 3 does not - shows just 1 thin line.

**Comment by jrobinso** [comment]
Yes, its strange, it only seems to be a problem with the lowest resolution.

**Comment by jrobinso** [comment]
This is how subtle the port from Java can be.  There are 2 representations of blocks in the file, the 2v3 format happend to use "type 2" which apparently is not used much elsewhere.   The bug was caused by the lack of a "floor" function on this integer division
i/w  vs  Math.floor(i / w);   
The floor happens automatically in Java
